services:
  traefik:
    restart: always
    image: traefik:v3.0
    command:
      - --configFile=/etc/traefik/traefik.toml
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./conf:/conf:ro
      - ./certificates/acme.json:/certificates/acme.json
networks:
  traefik-public:
    external: true