# -----------------------
# Nginx Dockerfile (supervisor)
# Version: 0.1.3
# https://nginx.org/en/docs/
# Author: @azataiot
# Date: 2024-05-25
# ----------------
ARG VERSION=0.1.4
ARG BASE_IMAGE=azataiot/alpine:latest
FROM ${BASE_IMAGE} as builder
ENV LANG en_US.utf8
RUN set -eux; \
	\
	apk update; \
    apk upgrade; \
    apk add --no-cache \
        nginx \
        supervisor

EXPOSE 80
VOLUME /etc/nginx/http.d/
VOLUME /etc/nginx/conf.d/
VOLUME /usr/share/nginx/html/

# Copy the nginx configuration file into the Docker image
COPY conf.d/ /etc/nginx/conf.d/
COPY http.d/ /etc/nginx/http.d/
COPY html/ /usr/share/nginx/html/

# Copy the docker-entrypoint.sh script into the Docker image
COPY ./scripts/entrypoint.sh /usr/local/bin/
COPY ./scripts/supervisord.conf /etc/supervisord.conf

# Make the script executable
RUN chmod +x /usr/local/bin/entrypoint.sh

# Use the script as the entrypoint
ENTRYPOINT ["entrypoint.sh"]
CMD ["supervisor"]
